"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useProgram } from "@/lib/ProgramContext";
import { fetchDemoBrief, buildTpp } from "@/lib/api";

type BuiltParam = {
  axis: string;
  label: string;
  metric: string;
  operator: string;
  threshold: number;
  units: string;
  weight: number;
  rationale: string;
};

export default function TppBuilderPage() {
  const { programId } = useProgram();
  const router = useRouter();
  const [brief, setBrief] = useState("");
  const [building, setBuilding] = useState(false);
  const [result, setResult] = useState<{
    used_llm: boolean;
    model: string;
    params: BuiltParam[];
  } | null>(null);

  useEffect(() => {
    fetchDemoBrief().then(setBrief).catch(() => {});
  }, []);

  async function run() {
    setBuilding(true);
    try {
      const r = await buildTpp(brief, programId);
      setResult(r as { used_llm: boolean; model: string; params: BuiltParam[] });
    } finally {
      setBuilding(false);
    }
  }

  return (
    <div className="max-w-3xl">
      <h1 className="mb-1 text-xl font-semibold">TPP Builder</h1>
      <p className="mb-4 text-sm text-neutral-400">
        Describe the program — indication, modality, competitive bar, go/no-go logic —
        and the OS reasons out a structured, executable Target Product Profile.
      </p>

      <textarea
        value={brief}
        onChange={(e) => setBrief(e.target.value)}
        rows={7}
        className="w-full rounded border border-neutral-700 bg-neutral-900 p-3 text-sm text-neutral-100"
      />

      <div className="mt-3 flex items-center gap-3">
        <button
          onClick={run}
          disabled={building || !brief}
          className="rounded bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
        >
          {building ? "Reasoning…" : "Build TPP"}
        </button>
        {result && (
          <span className="text-xs text-neutral-500">
            {result.used_llm
              ? `Generated by ${result.model}`
              : "Generated by deterministic fallback (no API key set)"}
          </span>
        )}
      </div>

      {result && (
        <div className="mt-6">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="text-sm font-semibold">Proposed TPP ({result.params.length} parameters)</h2>
            <button
              onClick={() => router.push("/tpp")}
              className="text-sm text-emerald-400 hover:underline"
            >
              View in Tracker →
            </button>
          </div>
          <div className="space-y-3">
            {result.params.map((p, i) => (
              <div key={i} className="rounded border border-neutral-800 bg-neutral-900 p-3">
                <div className="flex items-baseline justify-between">
                  <span className="text-sm font-medium">{p.label}</span>
                  <span className="rounded bg-neutral-800 px-2 py-0.5 font-mono text-xs text-emerald-300">
                    {p.metric} {p.operator} {p.threshold}
                    {p.units}
                  </span>
                </div>
                <p className="mt-1 text-xs text-neutral-400">{p.rationale}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
